version = 1

exclude_patterns = [
  "**/*.min.*",
  "node_modules/**"
]
test_patterns = ["**test.jsx?", "**test.tsx?", "**test_*.py"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "jest",
    "nodejs",
    "browser"
  ]

[[analyzers]]
name = "python"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
