name: Push pipeline

concurrency:
  group: "dev-pages"
  cancel-in-progress: true

on:
  push:
    branches: ["dev"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info

      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz and generate critical CSS
        run: npx quartz build --no-serve

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 7

      - name: Install subfont
        run: npm install -g subfont
      - name: Make script executable
        run: chmod +x ./scripts/subfont.sh
      - name: Subset fonts
        run: sh ./scripts/subfont.sh

      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Publish to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ZONE_ID: ${{ vars.CLOUDFLARE_ZONE_ID }}
        run: |
          export BRANCH=${${{ github.ref }}#refs/heads/}
          npx wrangler pages deploy ./public --project-name=turntrout --branch $BRANCH
