name: Compress Images
on:
  push:
    branches: ["*"]
    paths:
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.webp"
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Calibre Image Action
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          pngQuality: "80"
          webpQuality: "80"
