name: Visual Testing

on:
  push:
    branches: ["lostpixel"]
  pull_request:
    branches: ["lostpixel"]

jobs:
  visual-testing:
    # Using Ubuntu since it has the lowest per-minute rate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard:
          [
            1/20,
            2/20,
            3/20,
            4/20,
            5/20,
            6/20,
            7/20,
            8/20,
            9/20,
            10/20,
            11/20,
            12/20,
            13/20,
            14/20,
            15/20,
            16/20,
            17/20,
            18/20,
            19/20,
            20/20,
          ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ">=22"
          cache: "npm"

      # Restore Playwright's browser cache
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright and dependencies
        run: |
          npx playwright install --with-deps chromium webkit firefox
          npx playwright install-deps

      - name: Start local server
        run: |
          npx quartz build --serve &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV

      - name: Wait for server
        run: |
          # Wait for the server to be ready
          while ! nc -z localhost 8080; do
            sleep 0.1 # Check every 100ms
            # Check if server is still running
            if ! ps -p "$SERVER_PID" > /dev/null; then
              echo "Server failed to start"
              exit 1
            fi
          done
          echo "Server is ready"

      - name: Make folder
        run: mkdir -p ./lost-pixel

      - name: Run Playwright tests
        id: playwright
        continue-on-error: true
        run: npx playwright test --shard ${{ matrix.shard }} -g "(lostpixel)"
        env:
          CI: true
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Sanitize shard name
        run: echo "SANITIZED_SHARD=${MATRIX_SHARD%%/*}" >> $GITHUB_ENV
        env:
          MATRIX_SHARD: ${{ matrix.shard }}

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces-${{ env.SANITIZED_SHARD }}
          path: test-results/
          retention-days: 7

      - name: Run LostPixel
        if: always()
        uses: lost-pixel/lost-pixel@v3.16.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
          LOST_PIXEL_PROJECT_ID: ${{ secrets.LOST_PIXEL_PROJECT_ID }}

      - name: Check Playwright status
        if: steps.playwright.outcome == 'failure'
        run: exit 1
